language: java
script: "mvn -B -s travis-settings.xml -P MySQLTest test "
services:
  - mysql
  - postgresql
addons:
    postgresql: "9.3"
jdk:
  - oraclejdk7
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
