language: java
dist: trusty
sudo: required
addons:
    postgresql: "9.6"
script: "mvn -B -s .travis-settings.xml -P DBs-OpenSource test "
services:
  - mysql
  - postgresql

jdk:
  - openjdk7
  - oraclejdk8
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql --version
before_script:
  