language: java
dist: trusty
sudo: required
script: "mvn -B -s .travis-settings.xml -P DBs-OpenSource test "
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.6"

# Allow the sudo command
sudo: true

jdk:
  - openjdk7
  - oraclejdk8
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql --version
before_script:
  # ... I install the good version (PgSQL 9.6 Postgis 2.3)
    - sudo apt-get install postgresql-9.6-postgis-2.3 postgis -y -q
