language: java
dist: trusty
sudo: required
script: "mvn -B -s travis-settings.xml -P DBs-PostgresTest test "
services:
  - mysql
  - postgresql
jdk:
  - oraclejdk7
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql --version
  - psql -U postgres -c 'create extension postgis;'
  - psql -U postgres -c 'create extension postgis_topology;'
before_script: