language: java
dist: trusty
sudo: required
script: "mvn -B -s travis-settings.xml -P DBs-OpenSource test "
services:
  - mysql
  - postgresql
addons:
    postgresql: "9.6"
jdk:
  - oraclejdk7
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql --version
before_script:
  - psql -U postgres -c 'create extension postgis;'