language: java
dist: trusty
sudo: required
script: "mvn -B -s .travis-settings.xml -P DBs-OpenSource,ClusteredDBTest test "
services:
  - mysql
  - postgresql
jdk:
  - openjdk7
  - oraclejdk8
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql --version
before_script: