language: java
## YAML Template.
---
services:
  - mysql
  - postgresql
jdk:
  - oraclejdk7
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - psql -c 'create database dbvtest;' -U postgres
##script: mvn test -B -s travis-settings.xml -P DBs-OpenSource
