language: java
script: "mvn -B -s travis-settings.xml -P PostgresTest test "
services:
  - mysql
  - postgresql
jdk:
  - oraclejdk7
notifications:
  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - psql -c 'create database dbvtest;' -U postgres
