language: java
dist: xenial
sudo: true
addons:
    postgresql: '10'
    apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
script: "mvn -q -B -s .travis-settings.xml -P DBs-OpenSource,Cluster-OpenSource test "
services:
  - mysql
  - postgresql

jdk:
  - openjdk10
#  - oraclejdk8
#notifications:
#  email: false
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dbvtest_cluster;'
  - mysql -V
  - psql -c 'create database dbvtest;' -U postgres
  - psql -c 'create database dbvtest_cluster;' -U postgres
  - psql --version
before_script:
  